In [30]:
import projections
from importlib import reload
reload(projections)
projections.get_nf_d_projections()

{'Denver': 8.47,
 'Los Angeles Rams': 7.92,
 'Seattle': 7.81,
 'Jacksonville': 7.65,
 'Green Bay': 7.62,
 'San Francisco': 7.49,
 'New England': 7.3,
 'Atlanta': 7.17,
 'Buffalo': 6.98,
 'Carolina': 6.78,
 'Washington': 6.5,
 'New York Giants': 6.44,
 'Los Angeles Chargers': 6.25,
 'Miami': 6.2,
 'Minnesota': 6.12,
 'New York Jets': 6.05,
 'Pittsburgh': 5.91,
 'Baltimore': 5.89,
 'Philadelphia': 5.85,
 'Tampa Bay': 5.84,
 'Indianapolis': 5.65,
 'Detroit': 5.39,
 'Cincinnati': 5.34,
 'Tennessee': 5.31,
 'Kansas City': 5.13,
 'Houston': 5.13,
 'Arizona': 4.74,
 'Chicago': 4.64,
 'Las Vegas': 4.57,
 'New Orleans': 3.91,
 'Cleveland': 3.42,
 'Dallas': 3.09}

In [31]:
#!usr/bin/python3

import sys
import projections
import pandas as pd
from itertools import combinations
import numpy as np
from joblib import Parallel, delayed
import datetime
from collections import defaultdict

def remove_suffix(p, fanduel=False):

    if fanduel:
        p = p.replace(' Jr.', '')
        if fanduel_d.get(p.strip()):
            p = fanduel_d.get(p.strip())
    if (not fanduel) and defense.get(p.strip()):
        p = defense.get(p.strip())
    p = p.replace(' III', '')
    p = p.replace(' II', '')
    p = p.replace(' IV', '')
#     if p != 'Las Vegas':
#         p = p.replace(' V', '')
    p = p.replace('AJ ', 'A.J. ')
    p = p.replace('DJ Chark Jr.', 'D.J. Chark')
    p = p.replace('Marvin Jones Jr.', 'Marvin Jones')
    p = p.replace('Robert Griffin', 'Robert Griffin III')
    p = p.replace('DJ ', 'D.J. ')

    return p

defense = {
     'Steelers': 'Pittsburgh',
     'Chargers': 'Los Angeles Chargers',
     'Browns': 'Cleveland',
     'Vikings': 'Minnesota',
     'WAS Football Team': 'Washington',
     'Dolphins': 'Miami',
     'Lions': 'Detroit',
     'Patriots': 'New England',
     'Ravens': 'Baltimore',
     'Buccaneers': 'Tampa Bay',
     'Saints': 'New Orleans',
     'Chiefs': 'Kansas City',
     'Bengals': 'Cincinnati',
     'Texans': 'Houston',
     'Broncos': 'Denver',
     'Eagles': 'Philadelphia',
     'Panthers': 'Carolina',
     'Cardinals': 'Arizona',
     'Packers': 'Green Bay',
     'Titans': 'Tennessee',
     'Cowboys': 'Dallas',
     'Rams': 'Los Angeles Rams',
     'Seahawks': 'Seattle',
     'Jaguars': 'Jacksonville',
     'Falcons': 'Atlanta',
     'Jets': 'New York Jets',
     'Colts': 'Indianapolis',
     'Raiders': 'Las Vegas'
 }

fanduel_d = {
    'Pittsburgh Steelers': 'Pittsburgh',
    'Miami Dolphins': 'Miami',
    'Baltimore Ravens': 'Baltimore',
    'Cleveland Browns': 'Cleveland',
    'Los Angeles Chargers': 'Los Angeles Chargers',
    'Minnesota Vikings': 'Minnesota',
    'New England Patriots': 'New England',
    'Green Bay Packers': 'Green Bay',
    'New Orleans Saints': 'New Orleans',
    'Washington Football Team': 'Washington',
    'Indianapolis Colts': 'Indianapolis',
    'Philadelphia Eagles': 'Philadelphia',
    'Denver Broncos': 'Denver',
    'Tennessee Titans': 'Tennessee',
    'Cincinnati Bengals': 'Cincinnati',
    'Houston Texans': 'Houston',
    'Detroit Lions': 'Detroit',
    'Carolina Panthers': 'Carolina',
    'Jacksonville Jaguars': 'Jacksonville',
    'Atlanta Falcons': 'Atlanta',
    'New York Jets': 'New York Jets',
    'Dallas Cowboys': 'Dallas',
}

plyr_dict = projections.get_nf_projections()
plyr_dict.update(projections.get_nf_d_projections())

In [32]:
defense = {'d': 'DST', 'f': 'D'}
plyr_names = {'d': 'Name', 'f': 'Nickname'}
salary = {'d': 50000, 'f': 60000}

In [180]:
f = 'dk_showdown.csv'
df = pd.read_csv('inputs/' + f)
players = df['Name'].to_list()
players = {p: remove_suffix(p) for p in players}
df['Name'] = df['Name'].replace(players)
df = df.drop(df.loc[(df['Name'] == 'Josh Johnson') & (df.TeamAbbrev == 'NYJ')].index)
df = df.drop(df.loc[(df['Name'] == 'Ryan Griffin') & (df.TeamAbbrev == 'TB')].index)
df_cpt = df.loc[df['Roster Position']=='CPT']
df_flex = df.loc[df['Roster Position']=='FLEX']

In [33]:
f = 'fd_showdown.csv'
df = pd.read_csv('inputs/' + f)
df = df.drop(df.loc[(df['Nickname'] == 'Ryan Griffin') & (df.Team == 'TB')].index)
assert len(df) == len(df['Nickname'].unique())
players = df['Nickname'].to_list()
players = {p: remove_suffix(p, True) for p in players}
df['Nickname'] = df['Nickname'].replace(players)
df = df.set_index('Nickname')
df['Projection'] = pd.DataFrame.from_dict(plyr_dict, orient='index')
df = df.loc[df['Projection'] > 1]
df = df.reset_index()
df_cpt = df.copy()
df_flex = df.copy()

df_cpt.head()

,Nickname,Id,Position,First Name,Last Name,FPPG,Played,Salary,Game,Team,Opponent,Injury Indicator,Injury Details,Tier,Unnamed: 14,Unnamed: 15,Roster Position,Projection
0,Lamar Jackson,63855-63115,QB,Lamar,Jackson,22.142354,17.0,17000,BAL@LV,BAL,LV,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX,21.96
1,Derek Carr,63855-45859,QB,Derek,Carr,17.570000,16.0,14000,BAL@LV,LV,BAL,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX,16.61
2,Darren Waller,63855-25011,TE,Darren,Waller,14.068750,16.0,13000,BAL@LV,LV,BAL,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX,16.54
3,Josh Jacobs,63855-72731,RB,Josh,Jacobs,14.320000,15.0,12500,BAL@LV,LV,BAL,Q,Illness,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX,14.27
4,Ty'Son Williams,63855-60977,RB,Ty'Son,Williams,0.000000,1.0,12000,BAL@LV,BAL,LV,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX,12.86

In [34]:
df_cpt = df_cpt.set_index(plyr_names[f[0]])
df_cpt['Projection'] = pd.DataFrame.from_dict(plyr_dict, orient='index') * 1.5
df_cpt = df_cpt.reset_index()
df_cpt[plyr_names[f[0]]] = df_cpt[plyr_names[f[0]]].apply(lambda x: x.strip())
assert len(df_cpt[plyr_names[f[0]]]) == len(df_cpt[plyr_names[f[0]]].unique())
df_cpt.set_index([plyr_names[f[0]]], inplace=True)
df_cpt = df_cpt[df_cpt['Projection'] > 1]
df_cpt = df_cpt.reset_index()
df_pos_salary = df_cpt.groupby(['Salary'])['Projection'].agg([np.mean, np.max])
df_pos_salary = df_pos_salary.reset_index()
df_cpt = df_cpt.merge(df_pos_salary, on=['Salary'])
df_cpt = df_cpt[df_cpt['Projection'] == df_cpt['amax']]
df_cpt.set_index(plyr_names[f[0]], inplace=True)
df_cpt.head()

,Id,Position,First Name,Last Name,FPPG,Played,Salary,Game,Team,Opponent,Injury Indicator,Injury Details,Tier,Unnamed: 14,Unnamed: 15,Roster Position,Projection,mean,amax
Nickname,,,,,,,,,,,,,,,,,,,
Lamar Jackson,63855-63115,QB,Lamar,Jackson,22.142354,17.0,17000,BAL@LV,BAL,LV,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX,32.940,32.940,32.940
Derek Carr,63855-45859,QB,Derek,Carr,17.570000,16.0,14000,BAL@LV,LV,BAL,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX,24.915,24.915,24.915
Darren Waller,63855-25011,TE,Darren,Waller,14.068750,16.0,13000,BAL@LV,LV,BAL,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX,24.810,24.810,24.810
Josh Jacobs,63855-72731,RB,Josh,Jacobs,14.320000,15.0,12500,BAL@LV,LV,BAL,Q,Illness,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX,21.405,21.405,21.405
Ty'Son Williams,63855-60977,RB,Ty'Son,Williams,0.000000,1.0,12000,BAL@LV,BAL,LV,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX,19.290,19.290,19.290

In [35]:
df_flex = df_flex.set_index(plyr_names[f[0]])
df_flex['Projection'] = pd.DataFrame.from_dict(plyr_dict, orient='index')
df_flex = df_flex.reset_index()
df_flex[plyr_names[f[0]]] = df_flex[plyr_names[f[0]]].apply(lambda x: x.strip())
assert len(df_flex[plyr_names[f[0]]]) == len(df_flex[plyr_names[f[0]]].unique())
df_flex.set_index([plyr_names[f[0]]], inplace=True)
df_flex = df_flex[df_flex['Projection'] > 1]
df_flex = df_flex.reset_index()
df_pos_salary = df_flex.groupby(['Salary'])['Projection'].agg([np.mean, np.max])
df_pos_salary = df_pos_salary.reset_index()
df_flex = df_flex.merge(df_pos_salary, on=['Salary'])
df_flex = df_flex[(df_flex['Projection'] >= df_flex['mean'])]
df_flex.set_index(plyr_names[f[0]], inplace=True)
df_flex = df_flex.reset_index()
df_pos = df_flex.groupby(['Projection'])['Salary'].agg([np.min])['amin']
df_pos = df_pos.reset_index()
df_flex = df_flex.merge(df_pos, on=['Projection'])
df_flex = df_flex[(df_flex['Salary'] <= df_flex['amin'])]
df_flex.set_index(plyr_names[f[0]], inplace=True)
df_flex.head()

,Id,Position,First Name,Last Name,FPPG,Played,Salary,Game,Team,Opponent,Injury Indicator,Injury Details,Tier,Unnamed: 14,Unnamed: 15,Roster Position,Projection,mean,amax,amin
Nickname,,,,,,,,,,,,,,,,,,,,
Lamar Jackson,63855-63115,QB,Lamar,Jackson,22.142354,17.0,17000,BAL@LV,BAL,LV,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX,21.96,21.96,21.96,17000
Derek Carr,63855-45859,QB,Derek,Carr,17.570000,16.0,14000,BAL@LV,LV,BAL,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX,16.61,16.61,16.61,14000
Darren Waller,63855-25011,TE,Darren,Waller,14.068750,16.0,13000,BAL@LV,LV,BAL,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX,16.54,16.54,16.54,13000
Josh Jacobs,63855-72731,RB,Josh,Jacobs,14.320000,15.0,12500,BAL@LV,LV,BAL,Q,Illness,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX,14.27,14.27,14.27,12500
Ty'Son Williams,63855-60977,RB,Ty'Son,Williams,0.000000,1.0,12000,BAL@LV,BAL,LV,NaN,NaN,NaN,NaN,NaN,MVP - 1.5X Points/AnyFLEX,12.86,12.86,12.86,12000

In [36]:
flex_plyr_list = df_flex.to_dict(orient='index')
cpt_plyr_list = df_cpt.to_dict(orient='index')
flex_salary = {k: v['Salary'] for k,v in flex_plyr_list.items()}
cpt_salary = {k: v['Salary'] for k,v in cpt_plyr_list.items()}
flex_proj = {k: v['Projection'] for k,v in flex_plyr_list.items()}
cpt_proj = {k: v['Projection'] for k,v in cpt_plyr_list.items()}

def return_combos(plyr_list, count):
    return list(combinations(plyr_list, count))

flex_ct = {'d': 5, 'f': 4}

flex = return_combos(flex_plyr_list, flex_ct[f[0]])

total_list = []
for c in cpt_plyr_list.keys():
    for x in flex:
        if c not in x:
            total_list.append([c, *x])

df_total = pd.DataFrame(total_list)            
df_salary_flex = df_total.iloc[:,1:].replace(flex_salary)
df_salary_cpt = df_total.iloc[:,0].replace(cpt_salary)
df_proj_flex = df_total.iloc[:,1:].replace(flex_proj)
df_proj_cpt = df_total.iloc[:,0].replace(cpt_proj)
total_salary = df_salary_flex.sum(axis=1) + df_salary_cpt
total_projections = df_proj_flex.sum(axis=1) + df_proj_cpt
df_total['salary'] = total_salary
df_total['projection'] = total_projections
df_total = df_total.loc[df_total['salary'] <= salary[f[0]]]
df_total.sort_values('projection', ascending=False).head(10)

,0,1,2,3,4,salary,projection
309,Lamar Jackson,Darren Waller,Josh Jacobs,Marquise Brown,Bryan Edwards,59500,86.15
346,Lamar Jackson,Darren Waller,Ty'Son Williams,Mark Andrews,Bryan Edwards,60000,86.02
170,Lamar Jackson,Derek Carr,Mark Andrews,Marquise Brown,Bryan Edwards,59000,85.83
390,Lamar Jackson,Darren Waller,Mark Andrews,Marquise Brown,Bryan Edwards,58000,85.76
551,Lamar Jackson,Josh Jacobs,Mark Andrews,Marquise Brown,Henry Ruggs,60000,85.74
96,Lamar Jackson,Derek Carr,Josh Jacobs,Henry Ruggs,Bryan Edwards,60000,85.67
316,Lamar Jackson,Darren Waller,Josh Jacobs,Henry Ruggs,Bryan Edwards,59000,85.60
177,Lamar Jackson,Derek Carr,Mark Andrews,Henry Ruggs,Bryan Edwards,58500,85.28
397,Lamar Jackson,Darren Waller,Mark Andrews,Henry Ruggs,Bryan Edwards,57500,85.21
134,Lamar Jackson,Derek Carr,Ty'Son Williams,Marquise Brown,Bryan Edwards,60000,84.81